# Generated by Django 5.0.7 on 2024-08-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_date_event_enddate_remove_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
