# Generated by Django 5.0.7 on 2024-08-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ticket_ticket_type_alter_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
