# Generated by Django 5.0.7 on 2024-08-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticket_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='count',
        ),
    ]
