# Generated by Django 5.0.7 on 2024-08-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_ticket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
